### PR TITLE
enable access to skeleton script

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by lizmat** [comment]
Thanks!  But but, if you install the module now, the `h2c-skeleton` scripts gets installed, so you can just call it like `$ h2c-skeleton filename > output` ?

**Comment by tbrowder** [comment]
@lizmat, I don't see it on my system except under the .zef/store directory which should not be on a normal user's PATH. Where do you see it installed?

**Comment by lizmat** [comment]
Weird?  `skeleton` was installed, now `h2c-skeleton` is not?  It should be!

Am in the middle of some more feature adding, will come back to this later.

**Comment by tbrowder** [comment]
@lizmat, as I have found, somewhat by trial and error, anything in your source tree **bin** dir will be installed to bin in the installation location determined by zef. I think that will happen only if you put the right entries in the META6.json file.  Anything in your source tree **resources** dir will be installed in the zef-selected installation place. Again, I think that will only happen if the meta file is set up properly. 

In any case, the installation places on my hosts look very different if I install as a regular user or as root. In the root case all resource files get the CUR treatment (in which resources are associated with the host module) which seems not to be the case as a regular user installation.  Whereas, in my limited looks, bin files look to be overwritten without notice in all cases since there is no apparent association with the host module.

I know this is not a detailed and accurate response, but I am very interested in this issue and have been struggling with it for awhile.

**Comment by lizmat** [comment]
It appears that it needs to live in the `bin` directory, and **NOT** be mentioned at all in the META6.json.

Version 0.0.8 with fix on its way to CPAN now.

**Comment by tbrowder** [comment]
Good to know. But the issue of dup bin names is still a prob IMHO. Where should I file the issue, or should  I file one at all?

**Comment by lizmat** [comment]
If you look to what's *actually* in `install/share/perl6/site/bin`, you will see that it's a wrapper that allows you to specify `name`, `ver` and `auth`.  Looks like there's no support for `:$api` yet.

**Comment by tbrowder** [comment]
Thanks, I never thought of looking inside. As some young ones I know say,
"Bril!"

**Pull request closed without merging**
